#!/bin/bash
#Add usr/local/lib to search path of ld linker
#export LD_LIBRARY_PATH="/usr/local/lib"




################# SIMPLETEST_cv
if [ ”$1” = ”simpletest_cv” ];then
        #
        echo Compiling simpletest_cv
#Compile
g++ -I/opt/vc/include -L/opt/vc/lib \
-lopencv_core \
-lopencv_imgcodecs \
-lraspicam \
-lraspicam_cv \
-lmmal \
-lmmal_core \
-lmmal_util \
include/raspicam-0.1.6/utils/raspicam_cv_test.cpp -o bin/simpletest_cv_raspicam

echo run with command ./bin/simpletest_cv_raspicam
#Add usr/local/lib to search path of ld linker
export LD_LIBRARY_PATH="/usr/local/lib"
fi

################# SIMPLETEST_cv2
if [ ”$1” = ”simpletest_cv2” ];then
        #
        echo Compiling simpletest_cv2
#Compile
g++ `pkg-config --cflags --libs opencv` \
-I/opt/vc/include -L/opt/vc/lib \
-lraspicam \
-lraspicam_cv \
-lmmal \
-lmmal_core \
-lmmal_util \
include/raspicam-0.1.6/utils/raspicam_cv_test.cpp -o bin/simpletest_cv_raspicam

echo run with command ./bin/simpletest_cv_raspicam
#Add usr/local/lib to search path of ld linker
export LD_LIBRARY_PATH="/usr/local/lib"
fi



################# MASTER POSITIONING EXAMPLE (general) RPI
if [ ”$1” = ”positioning” ];then
	#
	echo Compiling general positioning program
#	g++ -std=c++11	\
g++ `pkg-config --cflags --libs opencv` \
-I/opt/vc/include -L/opt/vc/lib \
-lraspicam \
-lraspicam_cv \
-lmmal \
-lmmal_core \
-lmmal_util \
examples/positioning_rpi.cpp \
src/vopos.cpp \
src/angulation.cpp \
src/azipe.cpp \
src/opticalFlow.cpp \
src/homographyVO.cpp \
include/Quartic-master/quartic.cpp \
src/videoStream_RPI.cpp \
src/dataStream.cpp \
src/logger.cpp -o bin/positioning.out



echo NOT DONE YET
#Add usr/local/lib to search path of ld linker
export LD_LIBRARY_PATH="/usr/local/lib"

#	echo Run with command ./bin/positioning.out [option]
fi


################# MASTER POSITIONING EXAMPLE (general) RPI
if [ ”$1” = ”dataCollection” ];then
        #
        echo Compiling rpi data collection program
#       g++ -std=c++11  \
g++ `pkg-config --cflags --libs opencv` \
-I/opt/vc/include -L/opt/vc/lib \
-lraspicam \
-lraspicam_cv \
-lmmal \
-lmmal_core \
-lmmal_util \
examples/dataCollection_rpi.cpp \
src/videoStream_RPI.cpp \
src/dataStream.cpp \
src/logger.cpp -o \
bin/dataCollection.out



echo add usr/local/lib to search path of ld linker
echo e x p o r t LD_LIBRARY_PATH="/usr/local/lib"
#Add usr/local/lib to search path of ld linker
export LD_LIBRARY_PATH="/usr/local/lib"

#       echo Run with command ./bin/dataCollection.out [option]
fi






################# Speedtest (own) RPI
if [ ”$1” = ”speedtest” ];then
        #
        echo Compiling speedtest
#       g++ -std=c++11  \
g++ `pkg-config --cflags --libs opencv` \
-I/opt/vc/include -L/opt/vc/lib \
-lraspicam \
-lraspicam_cv \
-lmmal \
-lmmal_core \
-lmmal_util \
examples/speedtest_rpi.cpp \
src/videoStream_RPI.cpp \
src/logger.cpp \
-o bin/speedtest.out


#Add usr/local/lib to search path of ld linker
export LD_LIBRARY_PATH="/usr/local/lib"
       echo Run with command ./bin/speedtest.out
fi

## get images. used for calibration

if [ ”$1” = ”still” ];then
        #
        echo Compiling example: get still images

g++ -std=c++11  \
`pkg-config --cflags --libs opencv` \
-I/opt/vc/include -L/opt/vc/lib \
-lraspicam \
-lraspicam_cv \
-lmmal \
-lmmal_core \
-lmmal_util \
examples/getStillImages_rpi.cpp \
-o bin/getstill.out

echo Run with command ./bin/getstill.out
echo add lib path with e x p o r t LD_LIBRARY_PATH="/usr/local/lib"
fi

## i2c test functions
if [ ”$1” = ”i2c” ];then
        #
        echo Compiling i2c examples

#g++ examples/i2cSlave.cpp -lpthread -lpigpio -o bin/slaveTest.out
#g++ examples/i2cSlave_close.cpp -lpthread -lpigpio -o bin/slaveTest_close.out


g++ -std=c++11 examples/basici2cSlave.cpp -lpthread -lpigpio -o bin/slaveTest.out

       echo Run with command   sudo ./bin/slaveTest.out -option-
      # echo Close with command sudo ./bin/slaveTest_close.out
fi
